name: PeloPages Distributed Pipeline

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Start Ubuntu MySQL
        run: sudo systemctl start mysql.service
      - name: Build with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
          gradle-version: 6.4
      - name: Verify Build
        run: |
          ls -l application/business/build/libs
          ls -l application/category/build/libs
          echo "Build Fine"
      - name: Upload Artifact Business
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: application/business/build/libs/business-1.0-SNAPSHOT.jar
      - name: Upload Artifact Category
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: application/category/build/libs/category-1.0-SNAPSHOT.jar
      - name: build-docker-image-business
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: <docker-your-name>/business
          tags: distributed
          dockerfile: dockerfiles/Dockerfile-business
      - name: build-docker-image-category
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: <docker-user-name>/category
          tags: distributed
          dockerfile: dockerfiles/Dockerfile-category
  deploy-image-to-pks:
    needs: build-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Pivnet & PKS
        run: |
          sudo apt-get update
          wget -O pivnet github.com/pivotal-cf/pivnet-cli/releases/download/v0.0.55/pivnet-linux-amd64-0.0.55 && chmod +x pivnet && sudo mv pivnet /usr/local/bin
          pivnet login --api-token=${{ secrets.PKS_TOKEN }}
          pivnet download-product-files --product-slug='pivotal-container-service' --release-version='1.7.0' --product-file-id=646536
          sudo mv pks-linux-amd64-1.7.0-build.483 pks
          chmod +x pks
          sudo mv pks /usr/local/bin/
      - name: Install Kubectl
        run: |
          pivnet download-product-files --product-slug='pivotal-container-service' --release-version='1.7.0' --product-file-id=633728
          sudo mv  kubectl-linux-amd64-1.16.7 kubectl
          sudo mv kubectl /usr/local/bin/
      - name: PKS Login
        run: |
          pks login -a ${{ secrets.PKS_API }}   -u ${{ secrets.PKS_USERNAME }} -k -p ${{ secrets.PKS_PASSWORD }}
          pks get-credentials ${{ secrets.PKS_CLUSTER }}

          kubectl apply -f deployments/dist-namespace.yaml
          kubectl apply -f deployments/app-log-pvc.yaml
          kubectl apply -f deployments/app-log-pv.yaml
          kubectl apply -f deployments/mysql-pv.yaml
          kubectl apply -f deployments/mysql-pvc.yaml
          kubectl apply -f deployments/mysql-service.yaml
          kubectl apply -f deployments/mysql-secret.yaml
          kubectl apply -f deployments/mysql-deployment.yaml
          kubectl apply -f deployments/category-service.yaml
          kubectl apply -f deployments/category-deployment.yaml
          kubectl apply -f deployments/business-service.yaml
          kubectl apply -f deployments/business-deployment.yaml